build-clang: Exit upon failing to fetch upstream Clang updates
Treat all the same. :)

Signed-off-by: Albert I <krascgq@outlook.co.id>
Signed-off-by: Abhishek AN <darkabhi1520@gmail.com>

diff --git a/build-clang b/build-clang
--- a/build-clang
+++ b/build-clang
@@ -236,7 +236,7 @@ function git_sync() {(
     if [[ ${FOLDER} = "clang" ]]; then
         git fetch origin "${BRANCH}"-no-rebase
         add_remote upstream "${LLVM_ORG}$(basename "${FOLDER}")"
-        git fetch upstream
+        git fetch upstream || die "There was an error fetching updates for ${FOLDER}!"
         if [[ -n ${STOCK} ]]; then
             git reset --hard upstream/"${BRANCH}"
             [[ ${VERSION} -eq ${STABLE_VERSION} ]] && git cherry-pick 69ad28caf8 || git cherry-pick f50a8a1cf3
